### ISSUE TITLE
y-axis adjusting

### ISSUE THREAD

**Issue by tyokota** [ramnathv/rNVD3#4]
I've noticed that the y-Axis is adjusting for the multibar graph when data has multiple groups. When I use the legend to turn off certain groups, it potentially affects the y-bar scale. How can i set the y-bar scale from say 0-20?

**Comment by ramnathv** [comment]
NVD3 has added this feature in one of their [latest commits](https://github.com/novus/nvd3/commit/fa43a8388d49c2c4834bd370f739304bcdebba74). I don't think this has made it into their build version. I will update rCharts's version of NVD3 as soon as this gets released. If you are in a hurry, you could directly add the required javascript assets to the html.

If you wait for the new release, you should be able to do something like this to force the yAxis range.

``` S
require(rCharts)
hair_eye = subset(as.data.frame(HairEyeColor), Sex == "Male")
n1 <- nPlot(Freq ~ Hair, data = hair_eye, 
  group = 'Eye', type = 'multiBarChart'
)
n1$chart(yRange = c(0, 53))
```

Hope this helps.

**Comment by ramnathv** [comment]
Also, `rNVD3` is no longer under development. All features have been merged into [rCharts](http://github.com/ramnathv/rCharts), which is more general and accommodates multiple js charting libraries.

**Comment by tyokota** [comment]
Thank you, Ramnath. That would be great. Also, I am using the R package, rCharts. I incorrectly assumed this was the place to post this issue. Sorry!
